#!/usr/bin/env bash
# ticket.sh — Jira-style tickets that live in the repo, under docs/tickets/.
#
# Usage:
#   scripts/ticket.sh new "<title>" [--type story|bug|task|chore]
#                                   [--priority P1|P2|P3] [--reporter <name>]
#   scripts/ticket.sh index                 regenerate docs/tickets/INDEX.md
#   scripts/ticket.sh status <RS-nnn> <backlog|in-progress|in-review|done|wont-do>
#   scripts/ticket.sh list [--status <s>]
#
# A ticket records the ask in the requester's own words before anyone starts
# arguing about the solution — that "## Ask" block is the whole point, and it is
# the one section that must never be paraphrased.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

DIR="docs/tickets"
STATUSES="backlog in-progress in-review done wont-do"
TYPES="story bug task chore"
PRIORITIES="P1 P2 P3"

say() { printf '\033[1;36m▸ %s\033[0m\n' "$*" >&2; }
die() { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

usage() { sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; }

contains() { case " $1 " in *" $2 "*) return 0 ;; *) return 1 ;; esac; }

# One frontmatter value from a ticket file.
field() {
  awk -v k="$2" '
    NR == 1 && $0 == "---" { inf = 1; next }
    inf && $0 == "---"     { exit }
    inf && index($0, k ":") == 1 { sub(/^[^:]*: */, ""); print; exit }
  ' "$1"
}

ticket_file() {
  local id="$1" f
  f="$(ls "$DIR/$id"-*.md 2>/dev/null | head -1 || true)"
  [[ -n "$f" ]] || die "no ticket $id in $DIR/"
  printf '%s' "$f"
}

# ── new ───────────────────────────────────────────────────────────────────────

# Highest RS-nnn across the working tree AND origin/dev. Parallel Claude Code
# sessions each work in their own worktree off origin/dev, so a purely local
# scan hands two sessions the same number — the same trap that already bites
# version bumps and migration numbers here. Remote-aware allocation makes a
# collision rare; `index` catches the rest.
next_id() {
  local max=0 n
  git fetch --quiet origin dev 2>/dev/null || true
  # Process substitution, not a pipe: a `while read` on the right of a pipe runs
  # in a subshell and its `max` would be discarded.
  while read -r n; do
    if [[ -n "$n" ]] && (( 10#$n > max )); then max=$(( 10#$n )); fi
  done < <( { ls "$DIR" 2>/dev/null || true
              git ls-tree -r --name-only origin/dev -- "$DIR" 2>/dev/null | sed 's#.*/##' || true
            } | sed -nE 's/^RS-0*([0-9]+)-.*\.md$/\1/p' )
  printf 'RS-%03d' "$(( max + 1 ))"
}

slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//' \
    | cut -c1-52 \
    | sed -E 's/-+$//'
}

new_ticket() {
  local title="" type="task" priority="P2" reporter="${TICKET_REPORTER:-jinhu}"
  title="${1:?usage: ticket.sh new \"<title>\" [--type t] [--priority p]}"; shift || true
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --type)     type="${2:?--type needs a value}"; shift 2 ;;
      --priority) priority="${2:?--priority needs a value}"; shift 2 ;;
      --reporter) reporter="${2:?--reporter needs a value}"; shift 2 ;;
      *) die "unknown option '$1'" ;;
    esac
  done
  contains "$TYPES" "$type"          || die "type must be one of: $TYPES"
  contains "$PRIORITIES" "$priority" || die "priority must be one of: $PRIORITIES"

  mkdir -p "$DIR"
  local id file
  id="$(next_id)"
  file="$DIR/$id-$(slugify "$title").md"
  [[ -e "$file" ]] && die "$file already exists"

  cat > "$file" <<EOF
---
id: $id
title: $title
type: $type
status: backlog
priority: $priority
created: $(date +%Y-%m-%d)
reporter: $reporter
branch: $(git rev-parse --abbrev-ref HEAD)
pr:
version:
related: []
---

## Ask

> TODO: the requester's own words, verbatim. Do not paraphrase, tidy the
> grammar, or translate it into solution language — this is the record of what
> was actually asked.

## Context

TODO: what makes this worth doing, and what a reader needs to know to judge
the acceptance criteria.

## Acceptance criteria

- [ ] TODO: testable statements. "The X page shows Y", not "improve X".

## Out of scope

TODO: what was considered and deliberately left out, or "—".

## Notes

TODO: decisions made along the way, links to the spec/plan, surprises worth
recording. Delete if empty.
EOF
  say "Created $file"
  printf '%s\n' "$file"
}

# ── index ─────────────────────────────────────────────────────────────────────

reindex() {
  mkdir -p "$DIR"
  local out="$DIR/INDEX.md" f id status type priority title version dupes
  {
    printf '# Ticket index\n\n'
    printf 'Generated by `scripts/ticket.sh index` — do not edit by hand.\n'
    printf 'See [README.md](./README.md) for what the fields mean.\n\n'
    printf '| ID | Status | Type | Pri | Title | Shipped |\n'
    printf '|---|---|---|---|---|---|\n'
    for f in $(ls "$DIR"/RS-*.md 2>/dev/null | sort -r); do
      id="$(field "$f" id)"
      status="$(field "$f" status)"
      type="$(field "$f" type)"
      priority="$(field "$f" priority)"
      title="$(field "$f" title)"
      version="$(field "$f" version)"
      printf '| [%s](./%s) | %s | %s | %s | %s | %s |\n' \
        "$id" "$(basename "$f")" "${status:-?}" "${type:-?}" "${priority:-?}" \
        "${title:-?}" "${version:-—}"
    done
  } > "$out"

  # A duplicate id means two sessions allocated the same number — rename one
  # file and its `id:` line; nothing downstream disambiguates them.
  dupes="$(ls "$DIR"/RS-*.md 2>/dev/null | xargs -n1 basename 2>/dev/null \
    | sed -nE 's/^(RS-[0-9]+)-.*/\1/p' | sort | uniq -d || true)"
  [[ -n "$dupes" ]] && printf '\033[1;33m! duplicate ticket id(s): %s\033[0m\n' "$dupes" >&2

  say "Wrote $out ($(ls "$DIR"/RS-*.md 2>/dev/null | wc -l | tr -d ' ') tickets)."
}

# ── status ────────────────────────────────────────────────────────────────────

set_status() {
  local id="${1:?usage: ticket.sh status <RS-nnn> <status>}"
  local new="${2:?usage: ticket.sh status <RS-nnn> <status>}"
  contains "$STATUSES" "$new" || die "status must be one of: $STATUSES"
  local f; f="$(ticket_file "$id")"
  # BSD and GNU sed disagree on -i, so write through a temp file instead.
  local tmp; tmp="$(mktemp)"
  awk -v s="$new" '
    NR == 1 && $0 == "---" { inf = 1; print; next }
    inf && $0 == "---"     { inf = 0; print; next }
    inf && index($0, "status:") == 1 { print "status: " s; next }
    { print }
  ' "$f" > "$tmp"
  mv "$tmp" "$f"
  say "$id → $new"
  reindex
}

# ── list ──────────────────────────────────────────────────────────────────────

list() {
  local want="" f
  [[ "${1:-}" == "--status" ]] && want="${2:?--status needs a value}"
  for f in $(ls "$DIR"/RS-*.md 2>/dev/null | sort -r); do
    local st; st="$(field "$f" status)"
    [[ -n "$want" && "$st" != "$want" ]] && continue
    printf '%-8s %-12s %-6s %s\n' "$(field "$f" id)" "$st" "$(field "$f" priority)" "$(field "$f" title)"
  done
}

# ── main ──────────────────────────────────────────────────────────────────────

cmd="${1:-}"; shift || true
case "$cmd" in
  new)    new_ticket "$@" ;;
  index)  reindex ;;
  status) set_status "$@" ;;
  list)   list "$@" ;;
  -h|--help|"") usage ;;
  *) die "unknown command '$cmd' — try --help" ;;
esac
